### PR TITLE
✨ add subaccount support for hardware-wallet-cli

### PR DESCRIPTION
**Pull request by letmejustputthishere**
# Motivation

those changes are needed for the changes applied to `hardware-wallet-cli`  to properly work

# Changes

i've added support for subaccounts

# Tests

-

### CODE REVIEW

**Comment by letmejustputthishere** [comment]
@bitdivine @ielashi @peterpeterparker 

can we make an expection pls 😄 would be a shame if it goes to waste

**Comment by ielashi** [comment]
@letmejustputthishere I'll ask internally to make this repo open for external contributions. In the meantime, if it's ok with you, I'll copy your changes and create a new PR with it to unblock you.

**Comment by letmejustputthishere** [comment]
yes please, feel free to do that :)

**Comment by ielashi** [comment]
Here is a PR that is equivalent to this change (though implemented slightly differently): https://github.com/dfinity/ic-js/pull/138 cc @letmejustputthishere

**Comment by letmejustputthishere** [comment]
beautiful, thank you :)

**Pull request closed without merging**
