### PR TITLE
Release 0.4.0 on 2022-04-22

### PR DESCRIPTION
**Pull request by bitdivine**
# Motivation
We would like to release version 0.4.0 so that we can use the latest functionality.

# Changes
- Set release date in the CHANGELOG.md
- Summarized changes in the CHANGELOG.md

# Tests
None needed.

### CODE REVIEW

**Review by mstrasinskis — APPROVED** [review]
LGTM

**Comment by peterpeterparker** [comment]
@bitdivine @mstrasinskis do you plan to release?

if so please improve the CHANGELOG.md with the new features and fixes that have been implemented (it's what I meant with my last comment - i.e. what I wanted to tackle next week)

**Comment by bitdivine** [comment]
@peterpeterparker Yes, a new release is going out today, using this.  Are there changes not recorded in the changelog?

**Comment by peterpeterparker** [comment]
@bitdivine there are not yet recorded

**Comment by peterpeterparker** [comment]
@bitdivine there are not yet recorded

**Comment by bitdivine** [comment]
@peterpeterparker @mstrasinskis I have gone through the commits and filled in the changelog.  Have I summarized the changes accurately?

**Review by peterpeterparker — APPROVED** [review]
Thanks a lot!

**Pull request merged**
