### PR TITLE
L2-486: Neuron functionality compatible HW

### PR DESCRIPTION
**Pull request by lmuntanerDfinity**
# Motivation

Make neuron functionality compatible with hardware wallets.

# Changes

* Use the `hardwareWallet` flag in methods.
* Create a new method "XXXXHardwareWallet" for the compatible version.

# Tests

* Add a new test in all the methods for hardware wallet compatibility.

### CODE REVIEW

**Comment by lmuntanerDfinity** [comment]
@mstrasinskis @peterpeterparker please review

**Comment by lmuntanerDfinity** [comment]
With this we have feature parity with Flutter.

Pending fixes are in the Merge Neurons with Hardware wallet, as well as merge maturity. Both known issues also in Flutter.

**Review by peterpeterparker — APPROVED** [review]
LGTM, thanks

**Comment by peterpeterparker** [comment]
Merged it for you so that you got the nightly next week

**Comment by lmuntanerDfinity** [comment]
Thanks!

**Pull request merged**
